org:                    clawfire # change this with your own org
app:                    covid19passbook-doctoranytime
service:                passbook-sign

frameworkVersion:       '2'


provider:
  name:                 aws
  stage:                production
  region:               eu-central-1
  runtime:              nodejs12.x
  lambdaHashingVersion: 20201221
  layers:
      - arn:aws:lambda:eu-central-1:034541671702:layer:openssl-lambda:1

functions:
  sign:
    handler:            handler.sign
    name:               ${sls:stage}-passbook-sign
    description:        Sign a manifest.json for passbook signature
    events:
        - http:
            path:       sign
            method:     post
    environment:
        # put your key in this secret below. It should be a one liner with \n for new lines.
        KEY :           ${param:KEY}
        # and your key passphrase here
        KEY_PASSPHRASE : ${param:KEY_PASSPHRASE}
